-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 19:22:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema Avtokampi
-- -----------------------------------------------------
-- DROP DATABASE IF EXISTS Avtokampi ;

-- -----------------------------------------------------
-- Schema Avtokampi
-- -----------------------------------------------------
-- CREATE DATABASE IF NOT EXISTS Avtokampi DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Pravice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Pravice CASCADE;

CREATE SEQUENCE Pravice_seq;

CREATE TABLE IF NOT EXISTS Pravice (
  Pravica_ID INT NOT NULL DEFAULT NEXTVAL ('Pravice_seq'),
  Naziv VARCHAR(45) NULL,
  Opis VARCHAR(45) NULL,
  PRIMARY KEY (Pravica_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Uporabniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Uporabniki CASCADE;

CREATE SEQUENCE Uporabniki_seq;

CREATE TABLE IF NOT EXISTS Uporabniki (
  Uporabnik_ID INT NOT NULL DEFAULT NEXTVAL ('Uporabniki_seq'),
  Ime VARCHAR(45) NULL,
  Priimek VARCHAR(45) NULL,
  Slika BYTEA NULL,
  Telefon VARCHAR(45) NULL,
  Email VARCHAR(45) NULL,
  Geslo VARCHAR(45) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Pravice INT NOT NULL,
  PRIMARY KEY (Uporabnik_ID)
 ,
  CONSTRAINT fk_Uporabniki_Pravice
    FOREIGN KEY (Pravice)
    REFERENCES Pravice (Pravica_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Uporabniki_Pravice_idx ON Uporabniki (Pravice ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Drzave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Drzave CASCADE;

CREATE SEQUENCE Drzave_seq;

CREATE TABLE IF NOT EXISTS Drzave (
  Drzava_ID INT NOT NULL DEFAULT NEXTVAL ('Drzave_seq'),
  Naziv VARCHAR(45) NULL,
  PRIMARY KEY (Drzava_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Regije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Regije CASCADE;

CREATE SEQUENCE Regije_seq;

CREATE TABLE IF NOT EXISTS Regije (
  Regija_ID INT NOT NULL DEFAULT NEXTVAL ('Regije_seq'),
  Naziv VARCHAR(45) NULL,
  Drzava INT NOT NULL,
  PRIMARY KEY (Regija_ID)
 ,
  CONSTRAINT fk_Regije_Drzave1
    FOREIGN KEY (Drzava)
    REFERENCES Drzave (Drzava_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Regije_Drzave1_idx ON Regije (Drzava ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Lokacije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Lokacije CASCADE;

CREATE SEQUENCE Lokacije_seq;

CREATE TABLE IF NOT EXISTS Lokacije (
  Lokacija_ID INT NOT NULL DEFAULT NEXTVAL ('Lokacije_seq'),
  Naziv VARCHAR(45) NULL,
  Koordinata_X VARCHAR(45) NULL,
  Koordinata_Y VARCHAR(45) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Regija INT NOT NULL,
  PRIMARY KEY (Lokacija_ID)
 ,
  CONSTRAINT fk_Lokacije_Regije1
    FOREIGN KEY (Regija)
    REFERENCES Regije (Regija_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Lokacije_Regije1_idx ON Lokacije (Regija ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Avtokampi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Avtokampi CASCADE;

CREATE SEQUENCE Avtokampi_seq;

CREATE TABLE IF NOT EXISTS Avtokampi (
  Avtokamp_ID INT NOT NULL DEFAULT NEXTVAL ('Avtokampi_seq'),
  Naziv VARCHAR(100) NOT NULL,
  Opis VARCHAR(1000) NULL,
  Naslov VARCHAR(100) NULL,
  Telefon VARCHAR(45) NULL,
  Lokacija INT NOT NULL,
  PRIMARY KEY (Avtokamp_ID)
 ,
  CONSTRAINT fk_Avtokampi_Lokacije1
    FOREIGN KEY (Lokacija)
    REFERENCES Lokacije (Lokacija_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Avtokampi_Lokacije1_idx ON Avtokampi (Lokacija ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Kategorije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Kategorije CASCADE;

CREATE SEQUENCE Kategorije_seq;

CREATE TABLE IF NOT EXISTS Kategorije (
  Kategorija_ID INT NOT NULL DEFAULT NEXTVAL ('Kategorije_seq'),
  Naziv VARCHAR(45) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  PRIMARY KEY (Kategorija_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Kampirna_mesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Kampirna_mesta CASCADE;

CREATE SEQUENCE Kampirna_mesta_seq;

CREATE TABLE IF NOT EXISTS Kampirna_mesta (
  Kampirno_mesto_ID INT NOT NULL DEFAULT NEXTVAL ('Kampirna_mesta_seq'),
  Naziv VARCHAR(45) NULL,
  Velikost VARCHAR(45) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Avtokamp INT NOT NULL,
  Kategorija INT NOT NULL,
  PRIMARY KEY (Kampirno_mesto_ID)
 ,
  CONSTRAINT fk_Kampirna_mesta_Avtokampi1
    FOREIGN KEY (Avtokamp)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Kampirna_mesta_Kategorije1
    FOREIGN KEY (Kategorija)
    REFERENCES Kategorije (Kategorija_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Kampirna_mesta_Avtokampi1_idx ON Kampirna_mesta (Avtokamp ASC);
CREATE INDEX fk_Kampirna_mesta_Kategorije1_idx ON Kampirna_mesta (Kategorija ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Vrsta_kampiranja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Vrsta_kampiranja CASCADE;

CREATE SEQUENCE Vrsta_kampiranja_seq;

CREATE TABLE IF NOT EXISTS Vrsta_kampiranja (
  Vrsta_kampiranja_ID INT NOT NULL DEFAULT NEXTVAL ('Vrsta_kampiranja_seq'),
  Naziv VARCHAR(45) NULL,
  PRIMARY KEY (Vrsta_kampiranja_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Status_rezervacije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Status_rezervacije CASCADE;

CREATE SEQUENCE Status_rezervacije_seq;

CREATE TABLE IF NOT EXISTS Status_rezervacije (
  Status_rezervacije_ID INT NOT NULL DEFAULT NEXTVAL ('Status_rezervacije_seq'),
  Naziv VARCHAR(45) NULL,
  PRIMARY KEY (Status_rezervacije_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Rezervacije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Rezervacije CASCADE;

CREATE SEQUENCE Rezervacije_seq;

CREATE TABLE IF NOT EXISTS Rezervacije (
  Rezervacija_ID INT NOT NULL DEFAULT NEXTVAL ('Rezervacije_seq'),
  Trajanje_Od TIMESTAMP(0) NULL,
  Trajanje_Do TIMESTAMP(0) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Uporabnik INT NOT NULL,
  Avtokamp INT NOT NULL,
  Kampirno_mesto INT NOT NULL,
  Vrsta_kampiranja INT NOT NULL,
  Status_rezervacije INT NOT NULL,
  PRIMARY KEY (Rezervacija_ID)
 ,
  CONSTRAINT fk_Rezervacije_Uporabniki1
    FOREIGN KEY (Uporabnik)
    REFERENCES Uporabniki (Uporabnik_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Rezervacije_Avtokampi1
    FOREIGN KEY (Avtokamp)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Rezervacije_Kampirna_mesta1
    FOREIGN KEY (Kampirno_mesto)
    REFERENCES Kampirna_mesta (Kampirno_mesto_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Rezervacije_Vrsta_kampiranja1
    FOREIGN KEY (Vrsta_kampiranja)
    REFERENCES Vrsta_kampiranja (Vrsta_kampiranja_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Rezervacije_Status_rezervacije1
    FOREIGN KEY (Status_rezervacije)
    REFERENCES Status_rezervacije (Status_rezervacije_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Rezervacije_Uporabniki1_idx ON Rezervacije (Uporabnik ASC);
CREATE INDEX fk_Rezervacije_Avtokampi1_idx ON Rezervacije (Avtokamp ASC);
CREATE INDEX fk_Rezervacije_Kampirna_mesta1_idx ON Rezervacije (Kampirno_mesto ASC);
CREATE INDEX fk_Rezervacije_Vrsta_kampiranja1_idx ON Rezervacije (Vrsta_kampiranja ASC);
CREATE INDEX fk_Rezervacije_Status_rezervacije1_idx ON Rezervacije (Status_rezervacije ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Kategorije_storitev`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Kategorije_storitev CASCADE;

CREATE SEQUENCE Kategorije_storitev_seq;

CREATE TABLE IF NOT EXISTS Kategorije_storitev (
  Kategorija_storitve_ID INT NOT NULL DEFAULT NEXTVAL ('Kategorije_storitev_seq'),
  Naziv VARCHAR(45) NULL,
  PRIMARY KEY (Kategorija_storitve_ID))
;


-- -----------------------------------------------------
-- Table `Avtokampi`.`Ceniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Ceniki CASCADE;

CREATE SEQUENCE Ceniki_seq;

CREATE TABLE IF NOT EXISTS Ceniki (
  Cenik_ID INT NOT NULL DEFAULT NEXTVAL ('Ceniki_seq'),
  Naziv VARCHAR(45) NULL,
  Cena DECIMAL(10,0) NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Avtokamp INT NOT NULL,
  PRIMARY KEY (Cenik_ID)
 ,
  CONSTRAINT fk_Ceniki_Avtokampi1
    FOREIGN KEY (Avtokamp)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Ceniki_Avtokampi1_idx ON Ceniki (Avtokamp ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Storitve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Storitve CASCADE;

CREATE SEQUENCE Storitve_seq;

CREATE TABLE IF NOT EXISTS Storitve (
  Storitev_ID INT NOT NULL DEFAULT NEXTVAL ('Storitve_seq'),
  Naziv VARCHAR(45) NULL,
  Kategorija_storitve INT NOT NULL,
  Cenik INT NOT NULL,
  PRIMARY KEY (Storitev_ID)
 ,
  CONSTRAINT fk_Storitve_Kategorije_storitev1
    FOREIGN KEY (Kategorija_storitve)
    REFERENCES Kategorije_storitev (Kategorija_storitve_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Storitve_Ceniki1
    FOREIGN KEY (Cenik)
    REFERENCES Ceniki (Cenik_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Storitve_Kategorije_storitev1_idx ON Storitve (Kategorija_storitve ASC);
CREATE INDEX fk_Storitve_Ceniki1_idx ON Storitve (Cenik ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Mnenja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Mnenja CASCADE;

CREATE SEQUENCE Mnenja_seq;

CREATE TABLE IF NOT EXISTS Mnenja (
  Mnenje_ID INT NOT NULL DEFAULT NEXTVAL ('Mnenja_seq'),
  Mnenje VARCHAR(1000) NULL,
  Ocena INT NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated_at TIMESTAMP(0) NULL,
  Uporabnik INT NOT NULL,
  Avtokamp INT NOT NULL,
  PRIMARY KEY (Mnenje_ID)
 ,
  CONSTRAINT fk_Mnenja_Uporabniki1
    FOREIGN KEY (Uporabnik)
    REFERENCES Uporabniki (Uporabnik_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Mnenja_Avtokampi1
    FOREIGN KEY (Avtokamp)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Mnenja_Uporabniki1_idx ON Mnenja (Uporabnik ASC);
CREATE INDEX fk_Mnenja_Avtokampi1_idx ON Mnenja (Avtokamp ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Slike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Slike CASCADE;

CREATE SEQUENCE Slike_seq;

CREATE TABLE IF NOT EXISTS Slike (
  Slika_ID INT NOT NULL DEFAULT NEXTVAL ('Slike_seq'),
  Slika BYTEA NULL,
  Created_at TIMESTAMP(0) NULL,
  Updated TIMESTAMP(0) NULL,
  Avtokamp INT NOT NULL,
  PRIMARY KEY (Slika_ID)
 ,
  CONSTRAINT fk_Slike_Avtokampi1
    FOREIGN KEY (Avtokamp)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Slike_Avtokampi1_idx ON Slike (Avtokamp ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Storitve_kampirnih_mest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Storitve_kampirnih_mest CASCADE;

CREATE SEQUENCE Storitve_kampirnih_mest_seq;

CREATE TABLE IF NOT EXISTS Storitve_kampirnih_mest (
  Storitve_kampirnih_mest_ID INT NOT NULL DEFAULT NEXTVAL ('Storitve_kampirnih_mest_seq'),
  Kampirno_mesto INT NOT NULL,
  Storitev INT NOT NULL,
  PRIMARY KEY (Storitve_kampirnih_mest_ID)
 ,
  CONSTRAINT fk_Storitve_kampirnih_mest_Kampirna_mesta1
    FOREIGN KEY (Kampirno_mesto)
    REFERENCES Kampirna_mesta (Kampirno_mesto_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Storitve_kampirnih_mest_Storitve1
    FOREIGN KEY (Storitev)
    REFERENCES Storitve (Storitev_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Storitve_kampirnih_mest_Kampirna_mesta1_idx ON Storitve_kampirnih_mest (Kampirno_mesto ASC);
CREATE INDEX fk_Storitve_kampirnih_mest_Storitve1_idx ON Storitve_kampirnih_mest (Storitev ASC);


-- -----------------------------------------------------
-- Table `Avtokampi`.`Soritve_cenikov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Soritve_cenikov CASCADE;

CREATE SEQUENCE Soritve_cenikov_seq;

CREATE TABLE IF NOT EXISTS Soritve_cenikov (
  Soritve_cenikov_ID INT NOT NULL DEFAULT NEXTVAL ('Soritve_cenikov_seq'),
  Ceniki_Cenik_ID INT NOT NULL,
  Storitve_Storitev_ID INT NOT NULL,
  Avtokampi_Avtokamp_ID INT NOT NULL,
  PRIMARY KEY (Soritve_cenikov_ID)
 ,
  CONSTRAINT fk_Soritve_cenikov_Ceniki1
    FOREIGN KEY (Ceniki_Cenik_ID)
    REFERENCES Ceniki (Cenik_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Soritve_cenikov_Storitve1
    FOREIGN KEY (Storitve_Storitev_ID)
    REFERENCES Storitve (Storitev_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Soritve_cenikov_Avtokampi1
    FOREIGN KEY (Avtokampi_Avtokamp_ID)
    REFERENCES Avtokampi (Avtokamp_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_Soritve_cenikov_Ceniki1_idx ON Soritve_cenikov (Ceniki_Cenik_ID ASC);
CREATE INDEX fk_Soritve_cenikov_Storitve1_idx ON Soritve_cenikov (Storitve_Storitev_ID ASC);
CREATE INDEX fk_Soritve_cenikov_Avtokampi1_idx ON Soritve_cenikov (Avtokampi_Avtokamp_ID ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
